#!/bin/bash
count=0 
numero_da_linha=0
   while read linha ; do
 
numero_da_linha=$(($numero_da_linha+1)) 
   grep '\-\-\-' <<< $linha
 if [ $? == 0 ] ; then
  Titulo=$(grep '\-\-\-' <<< $linha | tr -d "-" | awk -F" " '{print $1}')
    unset count
fi 
 
   
     grep '\-\-\-' <<< $linha
 if [ $? == 1 ] ; then
     count=$(($count+1))
       echo Titulo do banco: $Titulo , Dentro do banco: $count , Numero da linha: $numero_da_linha 
fi 


   done < Banco-words.txt     
